### ISSUE TITLE
websocket ConnectionRefusedError

### ISSUE THREAD

**Issue by spacegoing** [sadighian/crypto-rl#30]
I am getting `ConnectionRefusedError` on my MBP M1 Chip. I also tried run `recorder` in a docker but still gets the same error message. Any idea where is this error coming from? Many thanks!
```
(cpt) changli@Changs-MBP crypto-rl % python recorder.py 
/opt/anaconda3/envs/cpt/lib/python3.8/site-packages/arctic/store/_pandas_ndarray_store.py:8: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  from pandas import Panel
[2022-03-21 01:16:57,221] Starting recorder with basket = [('BTC-USD', 'tBTCUSD'), ('ETH-USD', 'tETHUSD')]
[2022-03-21 01:16:57,231] Process started up for BTC-USD
/opt/anaconda3/envs/cpt/lib/python3.8/site-packages/arctic/store/_pandas_ndarray_store.py:8: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  from pandas import Panel
[2022-03-21 01:16:57,677] COINBASE client instantiated.
[2022-03-21 01:16:57,677] init_db_connection for BTC-USD...
[2022-03-21 01:16:57,677] Connecting to mongo: localhost (localhost)
[2022-03-21 01:16:57,721] BITFINEX client instantiated.
[2022-03-21 01:16:57,721] init_db_connection for tBTCUSD...
[2022-03-21 01:16:57,721] Connecting to mongo: localhost (localhost)
[2022-03-21 01:16:57,738] run() initiated on : BTC-USD
[2022-03-21 01:16:57,738] run() initiated on : tBTCUSD
[2022-03-21 01:16:57,739] Recorder: Gathered 2 tasks
[2022-03-21 01:16:57,758] Recorder: Finally done for BTC-USD and tBTCUSD.
Process Recorder-1:
Traceback (most recent call last):
  File "/opt/anaconda3/envs/cpt/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/changli/sg21CodeLab/Quant/Crypto/crypto-rl/recorder.py", line 59, in run
    loop.run_until_complete(tasks)
  File "/opt/anaconda3/envs/cpt/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/changli/sg21CodeLab/Quant/Crypto/crypto-rl/data_recorder/connector_components/client.py", line 49, in subscribe
    self.ws = await websockets.connect(self.ws_endpoint)
  File "/opt/anaconda3/envs/cpt/lib/python3.8/site-packages/websockets/legacy/client.py", line 650, in __await_impl_timeout__
    return await asyncio.wait_for(self.__await_impl__(), self.open_timeout)
  File "/opt/anaconda3/envs/cpt/lib/python3.8/asyncio/tasks.py", line 494, in wait_for
    return fut.result()
  File "/opt/anaconda3/envs/cpt/lib/python3.8/site-packages/websockets/legacy/client.py", line 654, in __await_impl__
    transport, protocol = await self._create_connection()
  File "/opt/anaconda3/envs/cpt/lib/python3.8/asyncio/base_events.py", line 1025, in create_connection
    raise exceptions[0]
  File "/opt/anaconda3/envs/cpt/lib/python3.8/asyncio/base_events.py", line 1010, in create_connection
    sock = await self._connect_sock(
  File "/opt/anaconda3/envs/cpt/lib/python3.8/asyncio/base_events.py", line 924, in _connect_sock
    await self.sock_connect(sock, address)
  File "/opt/anaconda3/envs/cpt/lib/python3.8/asyncio/selector_events.py", line 496, in sock_connect
    return await fut
  File "/opt/anaconda3/envs/cpt/lib/python3.8/asyncio/selector_events.py", line 528, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 61] Connect call failed ('0.0.0.0', 443)
[2022-03-21 01:17:02,745] Both Coinbase and Bitfinex are still warming up...
[2022-03-21 01:17:03,749] Both Coinbase and Bitfinex are still warming up...
```

**Comment by spacegoing** [comment]
The websocket link in config file needs to be updated
